# Generated by Django 3.1.7 on 2021-03-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_question', models.CharField(max_length=200)),
                ('question_answer', models.TextField()),
                ('question_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAQ.topic')),
            ],
        ),
    ]
