# Generated by Django 3.1.7 on 2021-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
