# Generated by Django 3.1.7 on 2021-03-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_topic_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
    ]
