# Generated by Django 3.1.7 on 2021-03-14 18:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('show_intro', models.BooleanField(default=True)),
                ('intro', tinymce.models.HTMLField()),
                ('show_process', models.BooleanField(default=True)),
                ('process', tinymce.models.HTMLField()),
                ('show_results', models.BooleanField(default=True)),
                ('results', tinymce.models.HTMLField()),
                ('show_its_time', models.BooleanField(default=True)),
                ('its_time', tinymce.models.HTMLField()),
                ('show_expert_advice', models.BooleanField(default=True)),
                ('expert_advice', tinymce.models.HTMLField()),
                ('show_approach', models.BooleanField(default=True)),
                ('approach', tinymce.models.HTMLField()),
                ('show_equipment', models.BooleanField(default=True)),
                ('equipment', tinymce.models.HTMLField()),
                ('show_guarantee', models.BooleanField(default=True)),
                ('guarantee', tinymce.models.HTMLField()),
                ('show_why_us', models.BooleanField(default=True)),
                ('why_us', tinymce.models.HTMLField()),
            ],
        ),
    ]
